drop table if exists loans;
drop table if exists members;
drop table if exists book_copy;
drop table if exists book_author;
drop table if exists books;
drop table if exists category;
drop table if exists authors;
drop table if exists library;


create table library (
    library_id int primary key generated always as identity,
    name varchar(32) not null
);

create table authors (
    author_id int primary key generated by default as identity, 
    name varchar(32) not null
    );

create table category(
    category_id int primary key generated always as identity, 
    name varchar(32) not null
    );
	
create table books(
    isbn varchar(10) primary key, 
    name varchar(32) not null, 
    publication_date date not null,
    category_id int not null references category(category_id)
    );

create table book_author(
    author_id int not null references authors(author_id), 
    isbn varchar(10) not null references books(isbn), 
    primary key(author_id, isbn)
    );

create table book_copy(
    copy_id int primary key generated always as identity, 
    isbn varchar(10) not null references books(isbn),
    library_id int not null references library(library_id)
    );

create table members(
    member_id int primary key generated always as identity, 
    name varchar(32) not null, 
    address varchar(32) not null, 
    email varchar(32) not null
    );

create table loans(
    member_id int not null references members(member_id), 
    copy_id int not null references book_copy(copy_id), 
    start_date date not null, 
    end_date date not null
    );
